In [1]:
import numpy as np

In [4]:
x = np.arange(1, 21)

In [5]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [7]:
x ** 2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400])

In [10]:
y = np.random.randint(100, size=(100))

In [11]:
y

array([66,  1, 82, 36, 72, 69,  8, 71, 64,  4, 16, 65, 41, 99, 93, 98, 84,
       26, 71,  7, 69, 28, 32, 84, 79, 88, 54, 82, 72, 12, 37, 93, 61, 69,
       60, 67, 29, 65, 19, 97, 16, 49, 55, 15, 77, 15, 76, 24, 99, 14, 78,
       89, 14, 17, 95, 37, 31, 13, 66, 85, 58, 78, 44, 64, 65, 69, 79, 33,
       84, 87, 27, 37, 35, 57, 21, 85, 96, 49, 78, 66, 84, 80, 79, 41, 10,
        4, 54, 50, 82, 68, 12,  9, 42, 51, 17, 97, 13, 23, 29, 72])

In [16]:
len(y[y <= y.max() * 0.8])

78

In [17]:
z = np.random.randint(10, size=(10, 10))

In [18]:
z

array([[4, 9, 6, 0, 4, 3, 8, 7, 0, 9],
       [1, 5, 8, 2, 8, 2, 8, 6, 0, 8],
       [1, 1, 4, 4, 3, 9, 0, 6, 0, 6],
       [4, 3, 0, 8, 8, 8, 8, 2, 8, 3],
       [9, 3, 0, 5, 7, 4, 7, 3, 3, 9],
       [5, 7, 2, 9, 1, 4, 8, 8, 3, 3],
       [7, 6, 7, 8, 3, 7, 7, 8, 7, 0],
       [7, 0, 6, 1, 4, 4, 4, 6, 3, 1],
       [7, 4, 9, 2, 3, 5, 2, 9, 2, 4],
       [2, 3, 0, 8, 5, 9, 4, 8, 2, 4]])

In [25]:
mittelwerte = z.mean(axis=1)

In [26]:
mittelwerte > 5

array([False, False, False,  True, False, False,  True, False, False,
       False])

In [33]:
z[mittelwerte>=5]

array([[4, 9, 6, 0, 4, 3, 8, 7, 0, 9],
       [4, 3, 0, 8, 8, 8, 8, 2, 8, 3],
       [9, 3, 0, 5, 7, 4, 7, 3, 3, 9],
       [5, 7, 2, 9, 1, 4, 8, 8, 3, 3],
       [7, 6, 7, 8, 3, 7, 7, 8, 7, 0]])

In [34]:
mittelwerte

array([5. , 4.8, 3.4, 5.2, 5. , 5. , 6. , 3.6, 4.7, 4.5])

In [39]:
a = np.random.randint(10, size=(100))

In [40]:
b = np.random.randint(10, size=(100))

In [41]:
a

array([3, 5, 2, 6, 0, 0, 3, 8, 6, 0, 2, 3, 6, 7, 9, 1, 6, 6, 6, 8, 1, 0,
       0, 6, 2, 5, 9, 8, 9, 3, 3, 2, 9, 9, 3, 2, 4, 6, 9, 0, 5, 7, 1, 4,
       4, 6, 0, 5, 4, 2, 3, 9, 3, 4, 5, 6, 2, 4, 7, 8, 5, 2, 7, 2, 7, 3,
       3, 5, 9, 0, 5, 7, 0, 3, 0, 0, 4, 6, 2, 3, 3, 6, 1, 0, 5, 1, 2, 2,
       0, 3, 4, 8, 0, 4, 8, 2, 4, 8, 8, 1])

In [42]:
b

array([8, 6, 2, 6, 9, 8, 6, 6, 4, 3, 1, 4, 9, 0, 5, 4, 5, 6, 6, 5, 4, 6,
       2, 3, 3, 7, 1, 0, 0, 9, 6, 5, 0, 0, 6, 5, 1, 2, 9, 0, 9, 1, 9, 5,
       0, 1, 3, 0, 0, 4, 4, 4, 8, 8, 7, 4, 7, 4, 9, 4, 5, 5, 4, 7, 3, 3,
       4, 2, 0, 8, 3, 6, 1, 7, 4, 6, 2, 7, 1, 3, 3, 6, 1, 5, 7, 2, 4, 6,
       6, 9, 4, 2, 3, 7, 3, 7, 8, 4, 1, 3])

In [43]:
a == b

array([False, False,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False,  True, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
        True,  True, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False])

In [47]:
index = [(num, i) for i, num in enumerate(a)]

In [50]:
a == b

array([False, False,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False,  True, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
        True,  True, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False])

In [53]:
np.array(index)[a == b]

array([[ 2,  2],
       [ 6,  3],
       [ 6, 17],
       [ 6, 18],
       [ 9, 38],
       [ 0, 39],
       [ 4, 57],
       [ 5, 60],
       [ 3, 65],
       [ 3, 79],
       [ 3, 80],
       [ 6, 81],
       [ 1, 82],
       [ 4, 90]])